/**
 * Comprehensive country mapping for ALL cities with complete flag coverage
 * Based on the complete city list from all uploaded files
 */

export interface CityInfo {
  name: string;
  countryCode: string;
  countryName: string;
}

/**
 * Complete city to country mapping with both codes and names
 * Covers ALL cities from the uploaded files
 */
export const cityMapping: Record<string, CityInfo> = {
// Kosovo
  'Pristina': { name: 'Pristina', countryCode: 'xk', countryName: 'Kosovo' },
  'Prizren': { name: 'Prizren', countryCode: 'xk', countryName: 'Kosovo' },
  'Peja': { name: 'Peja', countryCode: 'xk', countryName: 'Kosovo' },
  'Gjakova': { name: 'Gjakova', countryCode: 'xk', countryName: 'Kosovo' },
  'Mitrovica': { name: 'Mitrovica', countryCode: 'xk', countryName: 'Kosovo' },
  'Ferizaj': { name: 'Ferizaj', countryCode: 'xk', countryName: 'Kosovo' },
  'Gjilan': { name: 'Gjilan', countryCode: 'xk', countryName: 'Kosovo' },
  'Vushtrri': { name: 'Vushtrri', countryCode: 'xk', countryName: 'Kosovo' },
  'Suharekë': { name: 'Suharekë', countryCode: 'xk', countryName: 'Kosovo' },
  'Podujevë': { name: 'Podujevë', countryCode: 'xk', countryName: 'Kosovo' },

// Luxembourg
  'Luxembourg City': { name: 'Luxembourg City', countryCode: 'lu', countryName: 'Luxembourg' },
  'Differdange': { name: 'Differdange', countryCode: 'lu', countryName: 'Luxembourg' },
  'Dudelange': { name: 'Dudelange', countryCode: 'lu', countryName: 'Luxembourg' },
  'Ettelbruck': { name: 'Ettelbruck', countryCode: 'lu', countryName: 'Luxembourg' },
  'Diekirch': { name: 'Diekirch', countryCode: 'lu', countryName: 'Luxembourg' },
  'Wiltz': { name: 'Wiltz', countryCode: 'lu', countryName: 'Luxembourg' },
  'Echternach': { name: 'Echternach', countryCode: 'lu', countryName: 'Luxembourg' },

// Moldova
  'Chișinău': { name: 'Chișinău', countryCode: 'md', countryName: 'Moldova' },
  'Bălți': { name: 'Bălți', countryCode: 'md', countryName: 'Moldova' },
  'Bender': { name: 'Bender', countryCode: 'md', countryName: 'Moldova' },
  'Rîbnița': { name: 'Rîbnița', countryCode: 'md', countryName: 'Moldova' },
  'Cahul': { name: 'Cahul', countryCode: 'md', countryName: 'Moldova' },
  'Ungheni': { name: 'Ungheni', countryCode: 'md', countryName: 'Moldova' },
  'Soroca': { name: 'Soroca', countryCode: 'md', countryName: 'Moldova' },
  'Orhei': { name: 'Orhei', countryCode: 'md', countryName: 'Moldova' },
  'Dubăsari': { name: 'Dubăsari', countryCode: 'md', countryName: 'Moldova' },
  'Comrat': { name: 'Comrat', countryCode: 'md', countryName: 'Moldova' },

// Montenegro
  'Podgorica': { name: 'Podgorica', countryCode: 'me', countryName: 'Montenegro' },
  'Nikšić': { name: 'Nikšić', countryCode: 'me', countryName: 'Montenegro' },
  'Herceg Novi': { name: 'Herceg Novi', countryCode: 'me', countryName: 'Montenegro' },
  'Pljevlja': { name: 'Pljevlja', countryCode: 'me', countryName: 'Montenegro' },
  'Bijelo Polje': { name: 'Bijelo Polje', countryCode: 'me', countryName: 'Montenegro' },
  'Cetinje': { name: 'Cetinje', countryCode: 'me', countryName: 'Montenegro' },
  'Berane': { name: 'Berane', countryCode: 'me', countryName: 'Montenegro' },
  'Bar': { name: 'Bar', countryCode: 'me', countryName: 'Montenegro' },
  'Kotor': { name: 'Kotor', countryCode: 'me', countryName: 'Montenegro' },
  'Tivat': { name: 'Tivat', countryCode: 'me', countryName: 'Montenegro' },

// North Macedonia
  'Skopje': { name: 'Skopje', countryCode: 'mk', countryName: 'North Macedonia' },
  'Bitola': { name: 'Bitola', countryCode: 'mk', countryName: 'North Macedonia' },
  'Kumanovo': { name: 'Kumanovo', countryCode: 'mk', countryName: 'North Macedonia' },
  'Prilep': { name: 'Prilep', countryCode: 'mk', countryName: 'North Macedonia' },
  'Tetovo': { name: 'Tetovo', countryCode: 'mk', countryName: 'North Macedonia' },
  'Veles': { name: 'Veles', countryCode: 'mk', countryName: 'North Macedonia' },
  'Ohrid': { name: 'Ohrid', countryCode: 'mk', countryName: 'North Macedonia' },
  'Gostivar': { name: 'Gostivar', countryCode: 'mk', countryName: 'North Macedonia' },
  'Štip': { name: 'Štip', countryCode: 'mk', countryName: 'North Macedonia' },
  'Strumica': { name: 'Strumica', countryCode: 'mk', countryName: 'North Macedonia' },

// Slovakia
  'Bratislava': { name: 'Bratislava', countryCode: 'sk', countryName: 'Slovakia' },
  'Košice': { name: 'Košice', countryCode: 'sk', countryName: 'Slovakia' },
  'Prešov': { name: 'Prešov', countryCode: 'sk', countryName: 'Slovakia' },
  'Žilina': { name: 'Žilina', countryCode: 'sk', countryName: 'Slovakia' },
  'Nitra': { name: 'Nitra', countryCode: 'sk', countryName: 'Slovakia' },
  'Trnava': { name: 'Trnava', countryCode: 'sk', countryName: 'Slovakia' },
  'Martin': { name: 'Martin', countryCode: 'sk', countryName: 'Slovakia' },
  'Trenčín': { name: 'Trenčín', countryCode: 'sk', countryName: 'Slovakia' },
  'Poprad': { name: 'Poprad', countryCode: 'sk', countryName: 'Slovakia' },
  'Prievidza': { name: 'Prievidza', countryCode: 'sk', countryName: 'Slovakia' },

// Slovenia
  'Ljubljana': { name: 'Ljubljana', countryCode: 'si', countryName: 'Slovenia' },
  'Maribor': { name: 'Maribor', countryCode: 'si', countryName: 'Slovenia' },
  'Celje': { name: 'Celje', countryCode: 'si', countryName: 'Slovenia' },
  'Kranj': { name: 'Kranj', countryCode: 'si', countryName: 'Slovenia' },
  'Velenje': { name: 'Velenje', countryCode: 'si', countryName: 'Slovenia' },
  'Koper': { name: 'Koper', countryCode: 'si', countryName: 'Slovenia' },
  'Novo Mesto': { name: 'Novo Mesto', countryCode: 'si', countryName: 'Slovenia' },
  'Ptuj': { name: 'Ptuj', countryCode: 'si', countryName: 'Slovenia' },
  'Trbovlje': { name: 'Trbovlje', countryCode: 'si', countryName: 'Slovenia' },
  'Kamnik': { name: 'Kamnik', countryCode: 'si', countryName: 'Slovenia' },

// Afghanistan
  'Kabul': { name: 'Kabul', countryCode: 'af', countryName: 'Afghanistan' },
  'Kandahar': { name: 'Kandahar', countryCode: 'af', countryName: 'Afghanistan' },
  'Herat': { name: 'Herat', countryCode: 'af', countryName: 'Afghanistan' },
  'Mazar-i-Sharif': { name: 'Mazar-i-Sharif', countryCode: 'af', countryName: 'Afghanistan' },
  'Jalalabad': { name: 'Jalalabad', countryCode: 'af', countryName: 'Afghanistan' },
  'Kunduz': { name: 'Kunduz', countryCode: 'af', countryName: 'Afghanistan' },
  'Ghazni': { name: 'Ghazni', countryCode: 'af', countryName: 'Afghanistan' },
  'Lashkar Gah': { name: 'Lashkar Gah', countryCode: 'af', countryName: 'Afghanistan' },
  'Taloqan': { name: 'Taloqan', countryCode: 'af', countryName: 'Afghanistan' },
  'Pul-e Khumri': { name: 'Pul-e Khumri', countryCode: 'af', countryName: 'Afghanistan' },

// Bahrain
  'Manama': { name: 'Manama', countryCode: 'bh', countryName: 'Bahrain' },
  'Riffa': { name: 'Riffa', countryCode: 'bh', countryName: 'Bahrain' },
  'Muharraq': { name: 'Muharraq', countryCode: 'bh', countryName: 'Bahrain' },
  'Budaiya': { name: 'Budaiya', countryCode: 'bh', countryName: 'Bahrain' },
  'Galali': { name: 'Galali', countryCode: 'bh', countryName: 'Bahrain' },

// Bangladesh
  'Dhaka': { name: 'Dhaka', countryCode: 'bd', countryName: 'Bangladesh' },
  'Chittagong': { name: 'Chittagong', countryCode: 'bd', countryName: 'Bangladesh' },
  'Khulna': { name: 'Khulna', countryCode: 'bd', countryName: 'Bangladesh' },
  'Rajshahi': { name: 'Rajshahi', countryCode: 'bd', countryName: 'Bangladesh' },
  'Sylhet': { name: 'Sylhet', countryCode: 'bd', countryName: 'Bangladesh' },
  'Mymensingh': { name: 'Mymensingh', countryCode: 'bd', countryName: 'Bangladesh' },
  'Barisal': { name: 'Barisal', countryCode: 'bd', countryName: 'Bangladesh' },
  'Rangpur': { name: 'Rangpur', countryCode: 'bd', countryName: 'Bangladesh' },
  'Narayanganj': { name: 'Narayanganj', countryCode: 'bd', countryName: 'Bangladesh' },
  'Gazipur': { name: 'Gazipur', countryCode: 'bd', countryName: 'Bangladesh' },

// Cambodia
  'Phnom Penh': { name: 'Phnom Penh', countryCode: 'kh', countryName: 'Cambodia' },
  'Battambang': { name: 'Battambang', countryCode: 'kh', countryName: 'Cambodia' },
  'Siem Reap': { name: 'Siem Reap', countryCode: 'kh', countryName: 'Cambodia' },
  'Sihanoukville': { name: 'Sihanoukville', countryCode: 'kh', countryName: 'Cambodia' },
  'Poipet': { name: 'Poipet', countryCode: 'kh', countryName: 'Cambodia' },
  'Kampong Cham': { name: 'Kampong Cham', countryCode: 'kh', countryName: 'Cambodia' },
  'Pursat': { name: 'Pursat', countryCode: 'kh', countryName: 'Cambodia' },
  'Ta Khmau': { name: 'Ta Khmau', countryCode: 'kh', countryName: 'Cambodia' },
  'Kampot': { name: 'Kampot', countryCode: 'kh', countryName: 'Cambodia' },
  'Kampong Chhnang': { name: 'Kampong Chhnang', countryCode: 'kh', countryName: 'Cambodia' },

// Jordan
  'Amman': { name: 'Amman', countryCode: 'jo', countryName: 'Jordan' },
  'Zarqa': { name: 'Zarqa', countryCode: 'jo', countryName: 'Jordan' },
  'Irbid': { name: 'Irbid', countryCode: 'jo', countryName: 'Jordan' },
  'Russeifa': { name: 'Russeifa', countryCode: 'jo', countryName: 'Jordan' },
  'Aqaba': { name: 'Aqaba', countryCode: 'jo', countryName: 'Jordan' },
  'Madaba': { name: 'Madaba', countryCode: 'jo', countryName: 'Jordan' },
  'Mafraq': { name: 'Mafraq', countryCode: 'jo', countryName: 'Jordan' },
  'Salt': { name: 'Salt', countryCode: 'jo', countryName: 'Jordan' },
  'Jerash': { name: 'Jerash', countryCode: 'jo', countryName: 'Jordan' },
  'Karak': { name: 'Karak', countryCode: 'jo', countryName: 'Jordan' },

// Kyrgyzstan
  'Bishkek': { name: 'Bishkek', countryCode: 'kg', countryName: 'Kyrgyzstan' },
  'Osh': { name: 'Osh', countryCode: 'kg', countryName: 'Kyrgyzstan' },
  'Jalal-Abad': { name: 'Jalal-Abad', countryCode: 'kg', countryName: 'Kyrgyzstan' },
  'Karakol': { name: 'Karakol', countryCode: 'kg', countryName: 'Kyrgyzstan' },
  'Tokmok': { name: 'Tokmok', countryCode: 'kg', countryName: 'Kyrgyzstan' },
  'Talas': { name: 'Talas', countryCode: 'kg', countryName: 'Kyrgyzstan' },
  'Naryn': { name: 'Naryn', countryCode: 'kg', countryName: 'Kyrgyzstan' },
  'Kant': { name: 'Kant', countryCode: 'kg', countryName: 'Kyrgyzstan' },
  'Batken': { name: 'Batken', countryCode: 'kg', countryName: 'Kyrgyzstan' },
  'Balykchy': { name: 'Balykchy', countryCode: 'kg', countryName: 'Kyrgyzstan' },

// Laos
  'Vientiane': { name: 'Vientiane', countryCode: 'la', countryName: 'Laos' },
  'Pakse': { name: 'Pakse', countryCode: 'la', countryName: 'Laos' },
  'Savannakhet': { name: 'Savannakhet', countryCode: 'la', countryName: 'Laos' },
  'Luang Prabang': { name: 'Luang Prabang', countryCode: 'la', countryName: 'Laos' },
  'Thakhek': { name: 'Thakhek', countryCode: 'la', countryName: 'Laos' },
  'Phonsavan': { name: 'Phonsavan', countryCode: 'la', countryName: 'Laos' },
  'Muang Xay': { name: 'Muang Xay', countryCode: 'la', countryName: 'Laos' },
  'Xam Neua': { name: 'Xam Neua', countryCode: 'la', countryName: 'Laos' },
  'Attapeu': { name: 'Attapeu', countryCode: 'la', countryName: 'Laos' },
  'Sekong': { name: 'Sekong', countryCode: 'la', countryName: 'Laos' },

// Lebanon
  'Beirut': { name: 'Beirut', countryCode: 'lb', countryName: 'Lebanon' },
  'Tripoli': { name: 'Tripoli', countryCode: 'lb', countryName: 'Lebanon' },
  'Sidon': { name: 'Sidon', countryCode: 'lb', countryName: 'Lebanon' },
  'Zahle': { name: 'Zahle', countryCode: 'lb', countryName: 'Lebanon' },
  'Tyre': { name: 'Tyre', countryCode: 'lb', countryName: 'Lebanon' },
  'Jounieh': { name: 'Jounieh', countryCode: 'lb', countryName: 'Lebanon' },
  'Baabda': { name: 'Baabda', countryCode: 'lb', countryName: 'Lebanon' },
  'Batroun': { name: 'Batroun', countryCode: 'lb', countryName: 'Lebanon' },
  'Baalbek': { name: 'Baalbek', countryCode: 'lb', countryName: 'Lebanon' },
  'Byblos': { name: 'Byblos', countryCode: 'lb', countryName: 'Lebanon' },

// Malaysia
  'Kuala Lumpur': { name: 'Kuala Lumpur', countryCode: 'my', countryName: 'Malaysia' },
  'Kuala Terengganu': { name: 'Kuala Terengganu', countryCode: 'my', countryName: 'Malaysia' },
  'Kangar': { name: 'Kangar', countryCode: 'my', countryName: 'Malaysia' },
  'Ipoh': { name: 'Ipoh', countryCode: 'my', countryName: 'Malaysia' },
  'Seremban': { name: 'Seremban', countryCode: 'my', countryName: 'Malaysia' },
  'Melaka': { name: 'Melaka', countryCode: 'my', countryName: 'Malaysia' },
  'Johor Bahru': { name: 'Johor Bahru', countryCode: 'my', countryName: 'Malaysia' },
  'Kuantan': { name: 'Kuantan', countryCode: 'my', countryName: 'Malaysia' },
  'Alor Setar': { name: 'Alor Setar', countryCode: 'my', countryName: 'Malaysia' },
  'Kota Bharu': { name: 'Kota Bharu', countryCode: 'my', countryName: 'Malaysia' },

// Myanmar
  'Yangon': { name: 'Yangon', countryCode: 'mm', countryName: 'Myanmar' },
  'Mandalay': { name: 'Mandalay', countryCode: 'mm', countryName: 'Myanmar' },
  'Naypyidaw': { name: 'Naypyidaw', countryCode: 'mm', countryName: 'Myanmar' },
  'Bago': { name: 'Bago', countryCode: 'mm', countryName: 'Myanmar' },
  'Pathein': { name: 'Pathein', countryCode: 'mm', countryName: 'Myanmar' },
  'Monywa': { name: 'Monywa', countryCode: 'mm', countryName: 'Myanmar' },
  'Sittwe': { name: 'Sittwe', countryCode: 'mm', countryName: 'Myanmar' },
  'Meiktila': { name: 'Meiktila', countryCode: 'mm', countryName: 'Myanmar' },
  'Taunggyi': { name: 'Taunggyi', countryCode: 'mm', countryName: 'Myanmar' },
  'Myitkyina': { name: 'Myitkyina', countryCode: 'mm', countryName: 'Myanmar' },

// Oman
  'Muscat': { name: 'Muscat', countryCode: 'om', countryName: 'Oman' },
  'Salalah': { name: 'Salalah', countryCode: 'om', countryName: 'Oman' },
  'Sohar': { name: 'Sohar', countryCode: 'om', countryName: 'Oman' },
  'Nizwa': { name: 'Nizwa', countryCode: 'om', countryName: 'Oman' },
  'Sur': { name: 'Sur', countryCode: 'om', countryName: 'Oman' },
  'Buraimi': { name: 'Buraimi', countryCode: 'om', countryName: 'Oman' },
  'Ibri': { name: 'Ibri', countryCode: 'om', countryName: 'Oman' },
  'Rustaq': { name: 'Rustaq', countryCode: 'om', countryName: 'Oman' },
  'Saham': { name: 'Saham', countryCode: 'om', countryName: 'Oman' },
  'Ibra': { name: 'Ibra', countryCode: 'om', countryName: 'Oman' },

// Qatar
  'Doha': { name: 'Doha', countryCode: 'qa', countryName: 'Qatar' },
  'Al Khor': { name: 'Al Khor', countryCode: 'qa', countryName: 'Qatar' },
  'Al Shahaniya': { name: 'Al Shahaniya', countryCode: 'qa', countryName: 'Qatar' },
  'Mesaieed': { name: 'Mesaieed', countryCode: 'qa', countryName: 'Qatar' },
  'Dukhan': { name: 'Dukhan', countryCode: 'qa', countryName: 'Qatar' },
  'Al Daayen': { name: 'Al Daayen', countryCode: 'qa', countryName: 'Qatar' },
  'Lusail': { name: 'Lusail', countryCode: 'qa', countryName: 'Qatar' },

// Singapore
  'Singapore': { name: 'Singapore', countryCode: 'sg', countryName: 'Singapore' },

// Syria
  'Damascus': { name: 'Damascus', countryCode: 'sy', countryName: 'Syria' },
  'Aleppo': { name: 'Aleppo', countryCode: 'sy', countryName: 'Syria' },
  'Homs': { name: 'Homs', countryCode: 'sy', countryName: 'Syria' },
  'Hama': { name: 'Hama', countryCode: 'sy', countryName: 'Syria' },
  'Latakia': { name: 'Latakia', countryCode: 'sy', countryName: 'Syria' },
  'Deir ez-Zor': { name: 'Deir ez-Zor', countryCode: 'sy', countryName: 'Syria' },
  'Raqqa': { name: 'Raqqa', countryCode: 'sy', countryName: 'Syria' },
  'Daraa': { name: 'Daraa', countryCode: 'sy', countryName: 'Syria' },
  'Idlib': { name: 'Idlib', countryCode: 'sy', countryName: 'Syria' },
  'Tartus': { name: 'Tartus', countryCode: 'sy', countryName: 'Syria' },

// Tajikistan
  'Dushanbe': { name: 'Dushanbe', countryCode: 'tj', countryName: 'Tajikistan' },
  'Khujand': { name: 'Khujand', countryCode: 'tj', countryName: 'Tajikistan' },
  'Kulob': { name: 'Kulob', countryCode: 'tj', countryName: 'Tajikistan' },
  'Bokhtar': { name: 'Bokhtar', countryCode: 'tj', countryName: 'Tajikistan' },
  'Istaravshan': { name: 'Istaravshan', countryCode: 'tj', countryName: 'Tajikistan' },
  'Tursunzoda': { name: 'Tursunzoda', countryCode: 'tj', countryName: 'Tajikistan' },
  'Vahdat': { name: 'Vahdat', countryCode: 'tj', countryName: 'Tajikistan' },
  'Isfara': { name: 'Isfara', countryCode: 'tj', countryName: 'Tajikistan' },
  'Konibodom': { name: 'Konibodom', countryCode: 'tj', countryName: 'Tajikistan' },
  'Panjakent': { name: 'Panjakent', countryCode: 'tj', countryName: 'Tajikistan' },

// Turkmenistan
  'Ashgabat': { name: 'Ashgabat', countryCode: 'tm', countryName: 'Turkmenistan' },
  'Turkmenabat': { name: 'Turkmenabat', countryCode: 'tm', countryName: 'Turkmenistan' },
  'Dashoguz': { name: 'Dashoguz', countryCode: 'tm', countryName: 'Turkmenistan' },
  'Mary': { name: 'Mary', countryCode: 'tm', countryName: 'Turkmenistan' },
  'Balkanabat': { name: 'Balkanabat', countryCode: 'tm', countryName: 'Turkmenistan' },
  'Tejen': { name: 'Tejen', countryCode: 'tm', countryName: 'Turkmenistan' },
  'Bayramaly': { name: 'Bayramaly', countryCode: 'tm', countryName: 'Turkmenistan' },
  'Atamyrat': { name: 'Atamyrat', countryCode: 'tm', countryName: 'Turkmenistan' },
  'Kaka': { name: 'Kaka', countryCode: 'tm', countryName: 'Turkmenistan' },
  'Gyzylgaya': { name: 'Gyzylgaya', countryCode: 'tm', countryName: 'Turkmenistan' },

// Uzbekistan
  'Tashkent': { name: 'Tashkent', countryCode: 'uz', countryName: 'Uzbekistan' },
  'Samarkand': { name: 'Samarkand', countryCode: 'uz', countryName: 'Uzbekistan' },
  'Namangan': { name: 'Namangan', countryCode: 'uz', countryName: 'Uzbekistan' },
  'Andijan': { name: 'Andijan', countryCode: 'uz', countryName: 'Uzbekistan' },
  'Bukhara': { name: 'Bukhara', countryCode: 'uz', countryName: 'Uzbekistan' },
  'Nukus': { name: 'Nukus', countryCode: 'uz', countryName: 'Uzbekistan' },
  'Qarshi': { name: 'Qarshi', countryCode: 'uz', countryName: 'Uzbekistan' },
  'Fergana': { name: 'Fergana', countryCode: 'uz', countryName: 'Uzbekistan' },
  'Jizzakh': { name: 'Jizzakh', countryCode: 'uz', countryName: 'Uzbekistan' },
  'Termiz': { name: 'Termiz', countryCode: 'uz', countryName: 'Uzbekistan' },

// Yemen
  'Sana': { name: 'Sana', countryCode: 'ye', countryName: 'Yemen' },
  'Aden': { name: 'Aden', countryCode: 'ye', countryName: 'Yemen' },
  'Taiz': { name: 'Taiz', countryCode: 'ye', countryName: 'Yemen' },
  'Al Hudaydah': { name: 'Al Hudaydah', countryCode: 'ye', countryName: 'Yemen' },
  'Ibb': { name: 'Ibb', countryCode: 'ye', countryName: 'Yemen' },
  'Dhamar': { name: 'Dhamar', countryCode: 'ye', countryName: 'Yemen' },
  'Saada': { name: 'Saada', countryCode: 'ye', countryName: 'Yemen' },
  'Marib': { name: 'Marib', countryCode: 'ye', countryName: 'Yemen' },
  'Hajjah': { name: 'Hajjah', countryCode: 'ye', countryName: 'Yemen' },
  'Al Mukalla': { name: 'Al Mukalla', countryCode: 'ye', countryName: 'Yemen' },

// Albania
  'Tirana': { name: 'Tirana', countryCode: 'al', countryName: 'Albania' },
  'Durrës': { name: 'Durrës', countryCode: 'al', countryName: 'Albania' },
  'Vlorë': { name: 'Vlorë', countryCode: 'al', countryName: 'Albania' },
  'Shkodër': { name: 'Shkodër', countryCode: 'al', countryName: 'Albania' },
  'Fier': { name: 'Fier', countryCode: 'al', countryName: 'Albania' },
  'Korçë': { name: 'Korçë', countryCode: 'al', countryName: 'Albania' },
  'Berat': { name: 'Berat', countryCode: 'al', countryName: 'Albania' },
  'Lushnjë': { name: 'Lushnjë', countryCode: 'al', countryName: 'Albania' },
  'Pogradec': { name: 'Pogradec', countryCode: 'al', countryName: 'Albania' },
  'Kavajë': { name: 'Kavajë', countryCode: 'al', countryName: 'Albania' },

// Armenia
  'Yerevan': { name: 'Yerevan', countryCode: 'am', countryName: 'Armenia' },
  'Gyumri': { name: 'Gyumri', countryCode: 'am', countryName: 'Armenia' },
  'Vanadzor': { name: 'Vanadzor', countryCode: 'am', countryName: 'Armenia' },
  'Vagharshapat': { name: 'Vagharshapat', countryCode: 'am', countryName: 'Armenia' },
  'Abovyan': { name: 'Abovyan', countryCode: 'am', countryName: 'Armenia' },
  'Kapan': { name: 'Kapan', countryCode: 'am', countryName: 'Armenia' },
  'Hrazdan': { name: 'Hrazdan', countryCode: 'am', countryName: 'Armenia' },
  'Artashat': { name: 'Artashat', countryCode: 'am', countryName: 'Armenia' },
  'Armavir': { name: 'Armavir', countryCode: 'am', countryName: 'Armenia' },
  'Gavar': { name: 'Gavar', countryCode: 'am', countryName: 'Armenia' },

// Austria
  'Vienna': { name: 'Vienna', countryCode: 'at', countryName: 'Austria' },
  'Graz': { name: 'Graz', countryCode: 'at', countryName: 'Austria' },
  'Linz': { name: 'Linz', countryCode: 'at', countryName: 'Austria' },
  'Salzburg': { name: 'Salzburg', countryCode: 'at', countryName: 'Austria' },
  'Innsbruck': { name: 'Innsbruck', countryCode: 'at', countryName: 'Austria' },
  'Klagenfurt': { name: 'Klagenfurt', countryCode: 'at', countryName: 'Austria' },
  'Villach': { name: 'Villach', countryCode: 'at', countryName: 'Austria' },
  'Wels': { name: 'Wels', countryCode: 'at', countryName: 'Austria' },
  'Sankt Pölten': { name: 'Sankt Pölten', countryCode: 'at', countryName: 'Austria' },
  'Dornbirn': { name: 'Dornbirn', countryCode: 'at', countryName: 'Austria' },

// Azerbaijan
  'Baku': { name: 'Baku', countryCode: 'az', countryName: 'Azerbaijan' },
  'Ganja': { name: 'Ganja', countryCode: 'az', countryName: 'Azerbaijan' },
  'Sumqayit': { name: 'Sumqayit', countryCode: 'az', countryName: 'Azerbaijan' },
  'Mingachevir': { name: 'Mingachevir', countryCode: 'az', countryName: 'Azerbaijan' },
  'Lankaran': { name: 'Lankaran', countryCode: 'az', countryName: 'Azerbaijan' },
  'Shirvan': { name: 'Shirvan', countryCode: 'az', countryName: 'Azerbaijan' },
  'Nakhchivan': { name: 'Nakhchivan', countryCode: 'az', countryName: 'Azerbaijan' },
  'Shaki': { name: 'Shaki', countryCode: 'az', countryName: 'Azerbaijan' },
  'Yevlakh': { name: 'Yevlakh', countryCode: 'az', countryName: 'Azerbaijan' },
  'Khachmaz': { name: 'Khachmaz', countryCode: 'az', countryName: 'Azerbaijan' },

// Belarus
  'Minsk': { name: 'Minsk', countryCode: 'by', countryName: 'Belarus' },
  'Gomel': { name: 'Gomel', countryCode: 'by', countryName: 'Belarus' },
  'Mogilev': { name: 'Mogilev', countryCode: 'by', countryName: 'Belarus' },
  'Vitebsk': { name: 'Vitebsk', countryCode: 'by', countryName: 'Belarus' },
  'Grodno': { name: 'Grodno', countryCode: 'by', countryName: 'Belarus' },
  'Brest': { name: 'Brest', countryCode: 'by', countryName: 'Belarus' },
  'Babruysk': { name: 'Babruysk', countryCode: 'by', countryName: 'Belarus' },
  'Baranovichi': { name: 'Baranovichi', countryCode: 'by', countryName: 'Belarus' },
  'Borisov': { name: 'Borisov', countryCode: 'by', countryName: 'Belarus' },
  'Pinsk': { name: 'Pinsk', countryCode: 'by', countryName: 'Belarus' },

// Belgium
  'Brussels': { name: 'Brussels', countryCode: 'be', countryName: 'Belgium' },
  'Antwerp': { name: 'Antwerp', countryCode: 'be', countryName: 'Belgium' },
  'Ghent': { name: 'Ghent', countryCode: 'be', countryName: 'Belgium' },
  'Charleroi': { name: 'Charleroi', countryCode: 'be', countryName: 'Belgium' },
  'Liège': { name: 'Liège', countryCode: 'be', countryName: 'Belgium' },
  'Bruges': { name: 'Bruges', countryCode: 'be', countryName: 'Belgium' },
  'Namur': { name: 'Namur', countryCode: 'be', countryName: 'Belgium' },
  'Leuven': { name: 'Leuven', countryCode: 'be', countryName: 'Belgium' },
  'Mons': { name: 'Mons', countryCode: 'be', countryName: 'Belgium' },
  'Aalst': { name: 'Aalst', countryCode: 'be', countryName: 'Belgium' },

// Bosnia and Herzegovina
  'Sarajevo': { name: 'Sarajevo', countryCode: 'ba', countryName: 'Bosnia and Herzegovina' },
  'Banja Luka': { name: 'Banja Luka', countryCode: 'ba', countryName: 'Bosnia and Herzegovina' },
  'Tuzla': { name: 'Tuzla', countryCode: 'ba', countryName: 'Bosnia and Herzegovina' },
  'Zenica': { name: 'Zenica', countryCode: 'ba', countryName: 'Bosnia and Herzegovina' },
  'Mostar': { name: 'Mostar', countryCode: 'ba', countryName: 'Bosnia and Herzegovina' },
  'Bijeljina': { name: 'Bijeljina', countryCode: 'ba', countryName: 'Bosnia and Herzegovina' },
  'Prijedor': { name: 'Prijedor', countryCode: 'ba', countryName: 'Bosnia and Herzegovina' },
  'Brčko': { name: 'Brčko', countryCode: 'ba', countryName: 'Bosnia and Herzegovina' },
  'Doboj': { name: 'Doboj', countryCode: 'ba', countryName: 'Bosnia and Herzegovina' },
  'Cazin': { name: 'Cazin', countryCode: 'ba', countryName: 'Bosnia and Herzegovina' },

// Bulgaria
  'Sofia': { name: 'Sofia', countryCode: 'bg', countryName: 'Bulgaria' },
  'Plovdiv': { name: 'Plovdiv', countryCode: 'bg', countryName: 'Bulgaria' },
  'Varna': { name: 'Varna', countryCode: 'bg', countryName: 'Bulgaria' },
  'Burgas': { name: 'Burgas', countryCode: 'bg', countryName: 'Bulgaria' },
  'Ruse': { name: 'Ruse', countryCode: 'bg', countryName: 'Bulgaria' },
  'Stara Zagora': { name: 'Stara Zagora', countryCode: 'bg', countryName: 'Bulgaria' },
  'Pleven': { name: 'Pleven', countryCode: 'bg', countryName: 'Bulgaria' },
  'Sliven': { name: 'Sliven', countryCode: 'bg', countryName: 'Bulgaria' },
  'Dobrich': { name: 'Dobrich', countryCode: 'bg', countryName: 'Bulgaria' },
  'Shumen': { name: 'Shumen', countryCode: 'bg', countryName: 'Bulgaria' },

// Croatia
  'Zagreb': { name: 'Zagreb', countryCode: 'hr', countryName: 'Croatia' },
  'Split': { name: 'Split', countryCode: 'hr', countryName: 'Croatia' },
  'Rijeka': { name: 'Rijeka', countryCode: 'hr', countryName: 'Croatia' },
  'Osijek': { name: 'Osijek', countryCode: 'hr', countryName: 'Croatia' },
  'Zadar': { name: 'Zadar', countryCode: 'hr', countryName: 'Croatia' },
  'Pula': { name: 'Pula', countryCode: 'hr', countryName: 'Croatia' },
  'Slavonski Brod': { name: 'Slavonski Brod', countryCode: 'hr', countryName: 'Croatia' },
  'Karlovac': { name: 'Karlovac', countryCode: 'hr', countryName: 'Croatia' },
  'Varaždin': { name: 'Varaždin', countryCode: 'hr', countryName: 'Croatia' },
  'Šibenik': { name: 'Šibenik', countryCode: 'hr', countryName: 'Croatia' },

// Czech Republic
  'Prague': { name: 'Prague', countryCode: 'cz', countryName: 'Czech Republic' },
  'Brno': { name: 'Brno', countryCode: 'cz', countryName: 'Czech Republic' },
  'Ostrava': { name: 'Ostrava', countryCode: 'cz', countryName: 'Czech Republic' },
  'Plzeň': { name: 'Plzeň', countryCode: 'cz', countryName: 'Czech Republic' },
  'Liberec': { name: 'Liberec', countryCode: 'cz', countryName: 'Czech Republic' },
  'Olomouc': { name: 'Olomouc', countryCode: 'cz', countryName: 'Czech Republic' },
  'Ústí nad Labem': { name: 'Ústí nad Labem', countryCode: 'cz', countryName: 'Czech Republic' },
  'Hradec Králové': { name: 'Hradec Králové', countryCode: 'cz', countryName: 'Czech Republic' },
  'České Budějovice': { name: 'České Budějovice', countryCode: 'cz', countryName: 'Czech Republic' },
  'Pardubice': { name: 'Pardubice', countryCode: 'cz', countryName: 'Czech Republic' },

// Denmark
  'Copenhagen': { name: 'Copenhagen', countryCode: 'dk', countryName: 'Denmark' },
  'Aarhus': { name: 'Aarhus', countryCode: 'dk', countryName: 'Denmark' },
  'Odense': { name: 'Odense', countryCode: 'dk', countryName: 'Denmark' },
  'Aalborg': { name: 'Aalborg', countryCode: 'dk', countryName: 'Denmark' },
  'Esbjerg': { name: 'Esbjerg', countryCode: 'dk', countryName: 'Denmark' },
  'Randers': { name: 'Randers', countryCode: 'dk', countryName: 'Denmark' },
  'Kolding': { name: 'Kolding', countryCode: 'dk', countryName: 'Denmark' },
  'Horsens': { name: 'Horsens', countryCode: 'dk', countryName: 'Denmark' },
  'Vejle': { name: 'Vejle', countryCode: 'dk', countryName: 'Denmark' },
  'Roskilde': { name: 'Roskilde', countryCode: 'dk', countryName: 'Denmark' },

// Estonia
  'Tallinn': { name: 'Tallinn', countryCode: 'ee', countryName: 'Estonia' },
  'Tartu': { name: 'Tartu', countryCode: 'ee', countryName: 'Estonia' },
  'Narva': { name: 'Narva', countryCode: 'ee', countryName: 'Estonia' },
  'Pärnu': { name: 'Pärnu', countryCode: 'ee', countryName: 'Estonia' },
  'Kohtla-Järve': { name: 'Kohtla-Järve', countryCode: 'ee', countryName: 'Estonia' },
  'Viljandi': { name: 'Viljandi', countryCode: 'ee', countryName: 'Estonia' },
  'Rakvere': { name: 'Rakvere', countryCode: 'ee', countryName: 'Estonia' },
  'Maardu': { name: 'Maardu', countryCode: 'ee', countryName: 'Estonia' },
  'Sillamäe': { name: 'Sillamäe', countryCode: 'ee', countryName: 'Estonia' },
  'Kuressaare': { name: 'Kuressaare', countryCode: 'ee', countryName: 'Estonia' },

// Finland
  'Helsinki': { name: 'Helsinki', countryCode: 'fi', countryName: 'Finland' },
  'Espoo': { name: 'Espoo', countryCode: 'fi', countryName: 'Finland' },
  'Tampere': { name: 'Tampere', countryCode: 'fi', countryName: 'Finland' },
  'Vantaa': { name: 'Vantaa', countryCode: 'fi', countryName: 'Finland' },
  'Oulu': { name: 'Oulu', countryCode: 'fi', countryName: 'Finland' },
  'Turku': { name: 'Turku', countryCode: 'fi', countryName: 'Finland' },
  'Jyväskylä': { name: 'Jyväskylä', countryCode: 'fi', countryName: 'Finland' },
  'Lahti': { name: 'Lahti', countryCode: 'fi', countryName: 'Finland' },
  'Kuopio': { name: 'Kuopio', countryCode: 'fi', countryName: 'Finland' },
  'Pori': { name: 'Pori', countryCode: 'fi', countryName: 'Finland' },

// Georgia
  'Tbilisi': { name: 'Tbilisi', countryCode: 'ge', countryName: 'Georgia' },
  'Batumi': { name: 'Batumi', countryCode: 'ge', countryName: 'Georgia' },
  'Kutaisi': { name: 'Kutaisi', countryCode: 'ge', countryName: 'Georgia' },
  'Rustavi': { name: 'Rustavi', countryCode: 'ge', countryName: 'Georgia' },
  'Gori': { name: 'Gori', countryCode: 'ge', countryName: 'Georgia' },
  'Zugdidi': { name: 'Zugdidi', countryCode: 'ge', countryName: 'Georgia' },
  'Poti': { name: 'Poti', countryCode: 'ge', countryName: 'Georgia' },
  'Sokhumi': { name: 'Sokhumi', countryCode: 'ge', countryName: 'Georgia' },
  'Samtredia': { name: 'Samtredia', countryCode: 'ge', countryName: 'Georgia' },
  'Khashuri': { name: 'Khashuri', countryCode: 'ge', countryName: 'Georgia' },

// Greece
  'Athens': { name: 'Athens', countryCode: 'gr', countryName: 'Greece' },
  'Thessaloniki': { name: 'Thessaloniki', countryCode: 'gr', countryName: 'Greece' },
  'Patras': { name: 'Patras', countryCode: 'gr', countryName: 'Greece' },
  'Larissa': { name: 'Larissa', countryCode: 'gr', countryName: 'Greece' },
  'Volos': { name: 'Volos', countryCode: 'gr', countryName: 'Greece' },
  'Ioannina': { name: 'Ioannina', countryCode: 'gr', countryName: 'Greece' },
  'Kalamata': { name: 'Kalamata', countryCode: 'gr', countryName: 'Greece' },
  'Patras': { name: 'Patras', countryCode: 'gr', countryName: 'Greece' },
  'Chalcis': { name: 'Chalcis', countryCode: 'gr', countryName: 'Greece' },
  'Kavala': { name: 'Kavala', countryCode: 'gr', countryName: 'Greece' },

// Hungary
  'Budapest': { name: 'Budapest', countryCode: 'hu', countryName: 'Hungary' },
  'Debrecen': { name: 'Debrecen', countryCode: 'hu', countryName: 'Hungary' },
  'Szeged': { name: 'Szeged', countryCode: 'hu', countryName: 'Hungary' },
  'Miskolc': { name: 'Miskolc', countryCode: 'hu', countryName: 'Hungary' },
  'Pécs': { name: 'Pécs', countryCode: 'hu', countryName: 'Hungary' },
  'Győr': { name: 'Győr', countryCode: 'hu', countryName: 'Hungary' },
  'Nyíregyháza': { name: 'Nyíregyháza', countryCode: 'hu', countryName: 'Hungary' },
  'Kecskemét': { name: 'Kecskemét', countryCode: 'hu', countryName: 'Hungary' },
  'Székesfehérvár': { name: 'Székesfehérvár', countryCode: 'hu', countryName: 'Hungary' },
  'Szombathely': { name: 'Szombathely', countryCode: 'hu', countryName: 'Hungary' },

// Iraq
  'Baghdad': { name: 'Baghdad', countryCode: 'iq', countryName: 'Iraq' },
  'Basra': { name: 'Basra', countryCode: 'iq', countryName: 'Iraq' },
  'Mosul': { name: 'Mosul', countryCode: 'iq', countryName: 'Iraq' },
  'Erbil': { name: 'Erbil', countryCode: 'iq', countryName: 'Iraq' },
  'Najaf': { name: 'Najaf', countryCode: 'iq', countryName: 'Iraq' },
  'Karbala': { name: 'Karbala', countryCode: 'iq', countryName: 'Iraq' },
  'Nasiriyah': { name: 'Nasiriyah', countryCode: 'iq', countryName: 'Iraq' },
  'Amara': { name: 'Amara', countryCode: 'iq', countryName: 'Iraq' },
  'Kirkuk': { name: 'Kirkuk', countryCode: 'iq', countryName: 'Iraq' },
  'Wasit': { name: 'Wasit', countryCode: 'iq', countryName: 'Iraq' },

// Israel
  'Jerusalem': { name: 'Jerusalem', countryCode: 'il', countryName: 'Israel' },
  'Tel Aviv': { name: 'Tel Aviv', countryCode: 'il', countryName: 'Israel' },
  'Haifa': { name: 'Haifa', countryCode: 'il', countryName: 'Israel' },
  'Rishon LeZion': { name: 'Rishon LeZion', countryCode: 'il', countryName: 'Israel' },
  'Petah Tikva': { name: 'Petah Tikva', countryCode: 'il', countryName: 'Israel' },
  'Ashdod': { name: 'Ashdod', countryCode: 'il', countryName: 'Israel' },
  'Netanya': { name: 'Netanya', countryCode: 'il', countryName: 'Israel' },
  'Beersheba': { name: 'Beersheba', countryCode: 'il', countryName: 'Israel' },
  'Holon': { name: 'Holon', countryCode: 'il', countryName: 'Israel' },
  'Bnei Brak': { name: 'Bnei Brak', countryCode: 'il', countryName: 'Israel' },

// Kazakhstan
  'Nur-Sultan': { name: 'Nur-Sultan', countryCode: 'kz', countryName: 'Kazakhstan' },
  'Almaty': { name: 'Almaty', countryCode: 'kz', countryName: 'Kazakhstan' },
  'Shymkent': { name: 'Shymkent', countryCode: 'kz', countryName: 'Kazakhstan' },
  'Karaganda': { name: 'Karaganda', countryCode: 'kz', countryName: 'Kazakhstan' },
  'Aktobe': { name: 'Aktobe', countryCode: 'kz', countryName: 'Kazakhstan' },
  'Taraz': { name: 'Taraz', countryCode: 'kz', countryName: 'Kazakhstan' },
  'Pavlodar': { name: 'Pavlodar', countryCode: 'kz', countryName: 'Kazakhstan' },
  'Ust-Kamenogorsk': { name: 'Ust-Kamenogorsk', countryCode: 'kz', countryName: 'Kazakhstan' },
  'Semey': { name: 'Semey', countryCode: 'kz', countryName: 'Kazakhstan' },
  'Atyrau': { name: 'Atyrau', countryCode: 'kz', countryName: 'Kazakhstan' },

// South Korea
  'Seoul': { name: 'Seoul', countryCode: 'kr', countryName: 'South Korea' },
  'Busan': { name: 'Busan', countryCode: 'kr', countryName: 'South Korea' },
  'Incheon': { name: 'Incheon', countryCode: 'kr', countryName: 'South Korea' },
  'Daegu': { name: 'Daegu', countryCode: 'kr', countryName: 'South Korea' },
  'Daejeon': { name: 'Daejeon', countryCode: 'kr', countryName: 'South Korea' },
  'Gwangju': { name: 'Gwangju', countryCode: 'kr', countryName: 'South Korea' },
  'Suwon': { name: 'Suwon', countryCode: 'kr', countryName: 'South Korea' },
  'Ulsan': { name: 'Ulsan', countryCode: 'kr', countryName: 'South Korea' },
  'Changwon': { name: 'Changwon', countryCode: 'kr', countryName: 'South Korea' },
  'Goyang': { name: 'Goyang', countryCode: 'kr', countryName: 'South Korea' },

// Kuwait
  'Kuwait City': { name: 'Kuwait City', countryCode: 'kw', countryName: 'Kuwait' },
  'Al Ahmadi': { name: 'Al Ahmadi', countryCode: 'kw', countryName: 'Kuwait' },
  'Hawalli': { name: 'Hawalli', countryCode: 'kw', countryName: 'Kuwait' },
  'As Salimiyah': { name: 'As Salimiyah', countryCode: 'kw', countryName: 'Kuwait' },
  'Sabah as Salim': { name: 'Sabah as Salim', countryCode: 'kw', countryName: 'Kuwait' },
  'Al Farwaniyah': { name: 'Al Farwaniyah', countryCode: 'kw', countryName: 'Kuwait' },

// Latvia
  'Riga': { name: 'Riga', countryCode: 'lv', countryName: 'Latvia' },
  'Daugavpils': { name: 'Daugavpils', countryCode: 'lv', countryName: 'Latvia' },
  'Liepāja': { name: 'Liepāja', countryCode: 'lv', countryName: 'Latvia' },
  'Jelgava': { name: 'Jelgava', countryCode: 'lv', countryName: 'Latvia' },
  'Jūrmala': { name: 'Jūrmala', countryCode: 'lv', countryName: 'Latvia' },
  'Ventspils': { name: 'Ventspils', countryCode: 'lv', countryName: 'Latvia' },
  'Rēzekne': { name: 'Rēzekne', countryCode: 'lv', countryName: 'Latvia' },
  'Valmiera': { name: 'Valmiera', countryCode: 'lv', countryName: 'Latvia' },
  'Ogre': { name: 'Ogre', countryCode: 'lv', countryName: 'Latvia' },
  'Cēsis': { name: 'Cēsis', countryCode: 'lv', countryName: 'Latvia' },

// Lithuania
  'Vilnius': { name: 'Vilnius', countryCode: 'lt', countryName: 'Lithuania' },
  'Kaunas': { name: 'Kaunas', countryCode: 'lt', countryName: 'Lithuania' },
  'Klaipėda': { name: 'Klaipėda', countryCode: 'lt', countryName: 'Lithuania' },
  'Šiauliai': { name: 'Šiauliai', countryCode: 'lt', countryName: 'Lithuania' },
  'Panevėžys': { name: 'Panevėžys', countryCode: 'lt', countryName: 'Lithuania' },
  'Alytus': { name: 'Alytus', countryCode: 'lt', countryName: 'Lithuania' },
  'Marijampolė': { name: 'Marijampolė', countryCode: 'lt', countryName: 'Lithuania' },
  'Mažeikiai': { name: 'Mažeikiai', countryCode: 'lt', countryName: 'Lithuania' },
  'Jonava': { name: 'Jonava', countryCode: 'lt', countryName: 'Lithuania' },
  'Utena': { name: 'Utena', countryCode: 'lt', countryName: 'Lithuania' },

// Netherlands
  'Amsterdam': { name: 'Amsterdam', countryCode: 'nl', countryName: 'Netherlands' },
  'Rotterdam': { name: 'Rotterdam', countryCode: 'nl', countryName: 'Netherlands' },
  'The Hague': { name: 'The Hague', countryCode: 'nl', countryName: 'Netherlands' },
  'Utrecht': { name: 'Utrecht', countryCode: 'nl', countryName: 'Netherlands' },
  'Eindhoven': { name: 'Eindhoven', countryCode: 'nl', countryName: 'Netherlands' },
  'Tilburg': { name: 'Tilburg', countryCode: 'nl', countryName: 'Netherlands' },
  'Groningen': { name: 'Groningen', countryCode: 'nl', countryName: 'Netherlands' },
  'Almere': { name: 'Almere', countryCode: 'nl', countryName: 'Netherlands' },
  'Breda': { name: 'Breda', countryCode: 'nl', countryName: 'Netherlands' },
  'Nijmegen': { name: 'Nijmegen', countryCode: 'nl', countryName: 'Netherlands' },

// Norway
  'Oslo': { name: 'Oslo', countryCode: 'no', countryName: 'Norway' },
  'Bergen': { name: 'Bergen', countryCode: 'no', countryName: 'Norway' },
  'Stavanger': { name: 'Stavanger', countryCode: 'no', countryName: 'Norway' },
  'Trondheim': { name: 'Trondheim', countryCode: 'no', countryName: 'Norway' },
  'Drammen': { name: 'Drammen', countryCode: 'no', countryName: 'Norway' },
  'Fredrikstad': { name: 'Fredrikstad', countryCode: 'no', countryName: 'Norway' },
  'Porsgrunn': { name: 'Porsgrunn', countryCode: 'no', countryName: 'Norway' },
  'Skien': { name: 'Skien', countryCode: 'no', countryName: 'Norway' },
  'Kristiansand': { name: 'Kristiansand', countryCode: 'no', countryName: 'Norway' },
  'Tønsberg': { name: 'Tønsberg', countryCode: 'no', countryName: 'Norway' },

// Pakistan
  'Karachi': { name: 'Karachi', countryCode: 'pk', countryName: 'Pakistan' },
  'Lahore': { name: 'Lahore', countryCode: 'pk', countryName: 'Pakistan' },
  'Faisalabad': { name: 'Faisalabad', countryCode: 'pk', countryName: 'Pakistan' },
  'Rawalpindi': { name: 'Rawalpindi', countryCode: 'pk', countryName: 'Pakistan' },
  'Gujranwala': { name: 'Gujranwala', countryCode: 'pk', countryName: 'Pakistan' },
  'Peshawar': { name: 'Peshawar', countryCode: 'pk', countryName: 'Pakistan' },
  'Multan': { name: 'Multan', countryCode: 'pk', countryName: 'Pakistan' },
  'Hyderabad': { name: 'Hyderabad', countryCode: 'pk', countryName: 'Pakistan' },
  'Islamabad': { name: 'Islamabad', countryCode: 'pk', countryName: 'Pakistan' },
  'Quetta': { name: 'Quetta', countryCode: 'pk', countryName: 'Pakistan' },

// Poland
  'Warsaw': { name: 'Warsaw', countryCode: 'pl', countryName: 'Poland' },
  'Kraków': { name: 'Kraków', countryCode: 'pl', countryName: 'Poland' },
  'Łódź': { name: 'Łódź', countryCode: 'pl', countryName: 'Poland' },
  'Wrocław': { name: 'Wrocław', countryCode: 'pl', countryName: 'Poland' },
  'Poznań': { name: 'Poznań', countryCode: 'pl', countryName: 'Poland' },
  'Gdańsk': { name: 'Gdańsk', countryCode: 'pl', countryName: 'Poland' },
  'Szczecin': { name: 'Szczecin', countryCode: 'pl', countryName: 'Poland' },
  'Bydgoszcz': { name: 'Bydgoszcz', countryCode: 'pl', countryName: 'Poland' },
  'Lublin': { name: 'Lublin', countryCode: 'pl', countryName: 'Poland' },
  'Katowice': { name: 'Katowice', countryCode: 'pl', countryName: 'Poland' },

// Portugal
  'Lisbon': { name: 'Lisbon', countryCode: 'pt', countryName: 'Portugal' },
  'Porto': { name: 'Porto', countryCode: 'pt', countryName: 'Portugal' },
  'Vila Nova de Gaia': { name: 'Vila Nova de Gaia', countryCode: 'pt', countryName: 'Portugal' },
  'Amadora': { name: 'Amadora', countryCode: 'pt', countryName: 'Portugal' },
  'Braga': { name: 'Braga', countryCode: 'pt', countryName: 'Portugal' },
  'Funchal': { name: 'Funchal', countryCode: 'pt', countryName: 'Portugal' },
  'Coimbra': { name: 'Coimbra', countryCode: 'pt', countryName: 'Portugal' },
  'Setúbal': { name: 'Setúbal', countryCode: 'pt', countryName: 'Portugal' },
  'Almada': { name: 'Almada', countryCode: 'pt', countryName: 'Portugal' },
  'Agualva-Cacém': { name: 'Agualva-Cacém', countryCode: 'pt', countryName: 'Portugal' },

// Romania
  'Bucharest': { name: 'Bucharest', countryCode: 'ro', countryName: 'Romania' },
  'Cluj-Napoca': { name: 'Cluj-Napoca', countryCode: 'ro', countryName: 'Romania' },
  'Timișoara': { name: 'Timișoara', countryCode: 'ro', countryName: 'Romania' },
  'Iași': { name: 'Iași', countryCode: 'ro', countryName: 'Romania' },
  'Constanța': { name: 'Constanța', countryCode: 'ro', countryName: 'Romania' },
  'Craiova': { name: 'Craiova', countryCode: 'ro', countryName: 'Romania' },
  'Brașov': { name: 'Brașov', countryCode: 'ro', countryName: 'Romania' },
  'Galați': { name: 'Galați', countryCode: 'ro', countryName: 'Romania' },
  'Ploiești': { name: 'Ploiești', countryCode: 'ro', countryName: 'Romania' },
  'Oradea': { name: 'Oradea', countryCode: 'ro', countryName: 'Romania' },

// Saudi Arabia
  'Riyadh': { name: 'Riyadh', countryCode: 'sa', countryName: 'Saudi Arabia' },
  'Jeddah': { name: 'Jeddah', countryCode: 'sa', countryName: 'Saudi Arabia' },
  'Mecca': { name: 'Mecca', countryCode: 'sa', countryName: 'Saudi Arabia' },
  'Medina': { name: 'Medina', countryCode: 'sa', countryName: 'Saudi Arabia' },
  'Dammam': { name: 'Dammam', countryCode: 'sa', countryName: 'Saudi Arabia' },
  'Tabuk': { name: 'Tabuk', countryCode: 'sa', countryName: 'Saudi Arabia' },
  'Al Hofuf': { name: 'Al Hofuf', countryCode: 'sa', countryName: 'Saudi Arabia' },
  'Taif': { name: 'Taif', countryCode: 'sa', countryName: 'Saudi Arabia' },
  'Buraydah': { name: 'Buraydah', countryCode: 'sa', countryName: 'Saudi Arabia' },
  'Khobar': { name: 'Khobar', countryCode: 'sa', countryName: 'Saudi Arabia' },

// Sweden
  'Stockholm': { name: 'Stockholm', countryCode: 'se', countryName: 'Sweden' },
  'Gothenburg': { name: 'Gothenburg', countryCode: 'se', countryName: 'Sweden' },
  'Malmö': { name: 'Malmö', countryCode: 'se', countryName: 'Sweden' },
  'Uppsala': { name: 'Uppsala', countryCode: 'se', countryName: 'Sweden' },
  'Västerås': { name: 'Västerås', countryCode: 'se', countryName: 'Sweden' },
  'Örebro': { name: 'Örebro', countryCode: 'se', countryName: 'Sweden' },
  'Linköping': { name: 'Linköping', countryCode: 'se', countryName: 'Sweden' },
  'Helsingborg': { name: 'Helsingborg', countryCode: 'se', countryName: 'Sweden' },
  'Jönköping': { name: 'Jönköping', countryCode: 'se', countryName: 'Sweden' },
  'Norrköping': { name: 'Norrköping', countryCode: 'se', countryName: 'Sweden' },

// Switzerland
  'Zurich': { name: 'Zurich', countryCode: 'ch', countryName: 'Switzerland' },
  'Geneva': { name: 'Geneva', countryCode: 'ch', countryName: 'Switzerland' },
  'Basel': { name: 'Basel', countryCode: 'ch', countryName: 'Switzerland' },
  'Lausanne': { name: 'Lausanne', countryCode: 'ch', countryName: 'Switzerland' },
  'Bern': { name: 'Bern', countryCode: 'ch', countryName: 'Switzerland' },
  'Winterthur': { name: 'Winterthur', countryCode: 'ch', countryName: 'Switzerland' },
  'Lucerne': { name: 'Lucerne', countryCode: 'ch', countryName: 'Switzerland' },
  'St. Gallen': { name: 'St. Gallen', countryCode: 'ch', countryName: 'Switzerland' },
  'Lugano': { name: 'Lugano', countryCode: 'ch', countryName: 'Switzerland' },
  'Biel': { name: 'Biel', countryCode: 'ch', countryName: 'Switzerland' },

// Ukraine
  'Kyiv': { name: 'Kyiv', countryCode: 'ua', countryName: 'Ukraine' },
  'Kharkiv': { name: 'Kharkiv', countryCode: 'ua', countryName: 'Ukraine' },
  'Odessa': { name: 'Odessa', countryCode: 'ua', countryName: 'Ukraine' },
  'Dnipro': { name: 'Dnipro', countryCode: 'ua', countryName: 'Ukraine' },
  'Donetsk': { name: 'Donetsk', countryCode: 'ua', countryName: 'Ukraine' },
  'Zaporizhzhia': { name: 'Zaporizhzhia', countryCode: 'ua', countryName: 'Ukraine' },
  'Lviv': { name: 'Lviv', countryCode: 'ua', countryName: 'Ukraine' },
  'Kryvyi Rih': { name: 'Kryvyi Rih', countryCode: 'ua', countryName: 'Ukraine' },
  'Mykolaiv': { name: 'Mykolaiv', countryCode: 'ua', countryName: 'Ukraine' },
  'Mariupol': { name: 'Mariupol', countryCode: 'ua', countryName: 'Ukraine' },

// United Arab Emirates
  'Dubai': { name: 'Dubai', countryCode: 'ae', countryName: 'United Arab Emirates' },
  'Abu Dhabi': { name: 'Abu Dhabi', countryCode: 'ae', countryName: 'United Arab Emirates' },
  'Sharjah': { name: 'Sharjah', countryCode: 'ae', countryName: 'United Arab Emirates' },
  'Al Ain': { name: 'Al Ain', countryCode: 'ae', countryName: 'United Arab Emirates' },
  'Ajman': { name: 'Ajman', countryCode: 'ae', countryName: 'United Arab Emirates' },
  'Ras Al Khaimah': { name: 'Ras Al Khaimah', countryCode: 'ae', countryName: 'United Arab Emirates' },
  'Fujairah': { name: 'Fujairah', countryCode: 'ae', countryName: 'United Arab Emirates' },

// Vietnam
  'Ho Chi Minh City': { name: 'Ho Chi Minh City', countryCode: 'vn', countryName: 'Vietnam' },
  'Hanoi': { name: 'Hanoi', countryCode: 'vn', countryName: 'Vietnam' },
  'Da Nang': { name: 'Da Nang', countryCode: 'vn', countryName: 'Vietnam' },
  'Haiphong': { name: 'Haiphong', countryCode: 'vn', countryName: 'Vietnam' },
  'Can Tho': { name: 'Can Tho', countryCode: 'vn', countryName: 'Vietnam' },
  'Bien Hoa': { name: 'Bien Hoa', countryCode: 'vn', countryName: 'Vietnam' },
  'Nha Trang': { name: 'Nha Trang', countryCode: 'vn', countryName: 'Vietnam' },
  'Hue': { name: 'Hue', countryCode: 'vn', countryName: 'Vietnam' },
  'Vung Tau': { name: 'Vung Tau', countryCode: 'vn', countryName: 'Vietnam' },
  'Qui Nhon': { name: 'Qui Nhon', countryCode: 'vn', countryName: 'Vietnam' },

// Serbia
  'Belgrade': { name: 'Belgrade', countryCode: 'rs', countryName: 'Serbia' },
  'Novi Sad': { name: 'Novi Sad', countryCode: 'rs', countryName: 'Serbia' },
  'Nis': { name: 'Nis', countryCode: 'rs', countryName: 'Serbia' },
  'Kragujevac': { name: 'Kragujevac', countryCode: 'rs', countryName: 'Serbia' },
  'Novi Pazar': { name: 'Novi Pazar', countryCode: 'rs', countryName: 'Serbia' },
  'Subotica': { name: 'Subotica', countryCode: 'rs', countryName: 'Serbia' },
  'Kraljevo': { name: 'Kraljevo', countryCode: 'rs', countryName: 'Serbia' },
  'Jagodina': { name: 'Jagodina', countryCode: 'rs', countryName: 'Serbia' },
  'Pirot': { name: 'Pirot', countryCode: 'rs', countryName: 'Serbia' },
  'Zrenjanin': { name: 'Zrenjanin', countryCode: 'rs', countryName: 'Serbia' },

// China
  'Beijing': { name: 'Beijing', countryCode: 'cn', countryName: 'China' },
  'Shanghai': { name: 'Shanghai', countryCode: 'cn', countryName: 'China' },
  'Guangzhou': { name: 'Guangzhou', countryCode: 'cn', countryName: 'China' },
  'Shenzhen': { name: 'Shenzhen', countryCode: 'cn', countryName: 'China' },
  'Tianjin': { name: 'Tianjin', countryCode: 'cn', countryName: 'China' },
  'Chongqing': { name: 'Chongqing', countryCode: 'cn', countryName: 'China' },
  'Wuhan': { name: 'Wuhan', countryCode: 'cn', countryName: 'China' },
  'Chengdu': { name: 'Chengdu', countryCode: 'cn', countryName: 'China' },
  'Xian': { name: 'Xian', countryCode: 'cn', countryName: 'China' },
  'Nanjing': { name: 'Nanjing', countryCode: 'cn', countryName: 'China' },
  'Hangzhou': { name: 'Hangzhou', countryCode: 'cn', countryName: 'China' },
  'Shenyang': { name: 'Shenyang', countryCode: 'cn', countryName: 'China' },
  'Harbin': { name: 'Harbin', countryCode: 'cn', countryName: 'China' },
  'Qingdao': { name: 'Qingdao', countryCode: 'cn', countryName: 'China' },
  'Dalian': { name: 'Dalian', countryCode: 'cn', countryName: 'China' },
  'Zhengzhou': { name: 'Zhengzhou', countryCode: 'cn', countryName: 'China' },
  'Jinan': { name: 'Jinan', countryCode: 'cn', countryName: 'China' },
  'Changsha': { name: 'Changsha', countryCode: 'cn', countryName: 'China' },
  'Kunming': { name: 'Kunming', countryCode: 'cn', countryName: 'China' },
  'Suzhou': { name: 'Suzhou', countryCode: 'cn', countryName: 'China' },

// France
  'Paris': { name: 'Paris', countryCode: 'fr', countryName: 'France' },
  'Marseille': { name: 'Marseille', countryCode: 'fr', countryName: 'France' },
  'Lyon': { name: 'Lyon', countryCode: 'fr', countryName: 'France' },
  'Toulouse': { name: 'Toulouse', countryCode: 'fr', countryName: 'France' },
  'Nice': { name: 'Nice', countryCode: 'fr', countryName: 'France' },
  'Nantes': { name: 'Nantes', countryCode: 'fr', countryName: 'France' },
  'Strasbourg': { name: 'Strasbourg', countryCode: 'fr', countryName: 'France' },
  'Montpellier': { name: 'Montpellier', countryCode: 'fr', countryName: 'France' },
  'Bordeaux': { name: 'Bordeaux', countryCode: 'fr', countryName: 'France' },
  'Lille': { name: 'Lille', countryCode: 'fr', countryName: 'France' },
  'Rennes': { name: 'Rennes', countryCode: 'fr', countryName: 'France' },
  'Reims': { name: 'Reims', countryCode: 'fr', countryName: 'France' },
  'Le Havre': { name: 'Le Havre', countryCode: 'fr', countryName: 'France' },
  'Saint-Étienne': { name: 'Saint-Étienne', countryCode: 'fr', countryName: 'France' },
  'Toulon': { name: 'Toulon', countryCode: 'fr', countryName: 'France' },
  'Grenoble': { name: 'Grenoble', countryCode: 'fr', countryName: 'France' },
  'Dijon': { name: 'Dijon', countryCode: 'fr', countryName: 'France' },
  'Angers': { name: 'Angers', countryCode: 'fr', countryName: 'France' },
  'Nîmes': { name: 'Nîmes', countryCode: 'fr', countryName: 'France' },
  'Villeurbanne': { name: 'Villeurbanne', countryCode: 'fr', countryName: 'France' },

// Germany
  'Berlin': { name: 'Berlin', countryCode: 'de', countryName: 'Germany' },
  'Hamburg': { name: 'Hamburg', countryCode: 'de', countryName: 'Germany' },
  'Munich': { name: 'Munich', countryCode: 'de', countryName: 'Germany' },
  'Cologne': { name: 'Cologne', countryCode: 'de', countryName: 'Germany' },
  'Frankfurt': { name: 'Frankfurt', countryCode: 'de', countryName: 'Germany' },
  'Stuttgart': { name: 'Stuttgart', countryCode: 'de', countryName: 'Germany' },
  'Düsseldorf': { name: 'Düsseldorf', countryCode: 'de', countryName: 'Germany' },
  'Dortmund': { name: 'Dortmund', countryCode: 'de', countryName: 'Germany' },
  'Essen': { name: 'Essen', countryCode: 'de', countryName: 'Germany' },
  'Leipzig': { name: 'Leipzig', countryCode: 'de', countryName: 'Germany' },
  'Bremen': { name: 'Bremen', countryCode: 'de', countryName: 'Germany' },
  'Dresden': { name: 'Dresden', countryCode: 'de', countryName: 'Germany' },
  'Hanover': { name: 'Hanover', countryCode: 'de', countryName: 'Germany' },
  'Nuremberg': { name: 'Nuremberg', countryCode: 'de', countryName: 'Germany' },
  'Duisburg': { name: 'Duisburg', countryCode: 'de', countryName: 'Germany' },
  'Bochum': { name: 'Bochum', countryCode: 'de', countryName: 'Germany' },
  'Wuppertal': { name: 'Wuppertal', countryCode: 'de', countryName: 'Germany' },
  'Bielefeld': { name: 'Bielefeld', countryCode: 'de', countryName: 'Germany' },
  'Bonn': { name: 'Bonn', countryCode: 'de', countryName: 'Germany' },
  'Münster': { name: 'Münster', countryCode: 'de', countryName: 'Germany' },

// United Kingdom
  'London': { name: 'London', countryCode: 'gb', countryName: 'United Kingdom' },
  'Birmingham': { name: 'Birmingham', countryCode: 'gb', countryName: 'United Kingdom' },
  'Manchester': { name: 'Manchester', countryCode: 'gb', countryName: 'United Kingdom' },
  'Leeds': { name: 'Leeds', countryCode: 'gb', countryName: 'United Kingdom' },
  'Liverpool': { name: 'Liverpool', countryCode: 'gb', countryName: 'United Kingdom' },
  'Glasgow': { name: 'Glasgow', countryCode: 'gb', countryName: 'United Kingdom' },
  'Sheffield': { name: 'Sheffield', countryCode: 'gb', countryName: 'United Kingdom' },
  'Bristol': { name: 'Bristol', countryCode: 'gb', countryName: 'United Kingdom' },
  'Leicester': { name: 'Leicester', countryCode: 'gb', countryName: 'United Kingdom' },
  'Edinburgh': { name: 'Edinburgh', countryCode: 'gb', countryName: 'United Kingdom' },
  'Coventry': { name: 'Coventry', countryCode: 'gb', countryName: 'United Kingdom' },
  'Nottingham': { name: 'Nottingham', countryCode: 'gb', countryName: 'United Kingdom' },
  'Kingston upon Hull': { name: 'Kingston upon Hull', countryCode: 'gb', countryName: 'United Kingdom' },
  'Bradford': { name: 'Bradford', countryCode: 'gb', countryName: 'United Kingdom' },
  'Cardiff': { name: 'Cardiff', countryCode: 'gb', countryName: 'United Kingdom' },
  'Stoke-on-Trent': { name: 'Stoke-on-Trent', countryCode: 'gb', countryName: 'United Kingdom' },
  'Sunderland': { name: 'Sunderland', countryCode: 'gb', countryName: 'United Kingdom' },
  'Derby': { name: 'Derby', countryCode: 'gb', countryName: 'United Kingdom' },
  'Southampton': { name: 'Southampton', countryCode: 'gb', countryName: 'United Kingdom' },
  'Portsmouth': { name: 'Portsmouth', countryCode: 'gb', countryName: 'United Kingdom' },

// Spain
  'Madrid': { name: 'Madrid', countryCode: 'es', countryName: 'Spain' },
  'Barcelona': { name: 'Barcelona', countryCode: 'es', countryName: 'Spain' },
  'Valencia': { name: 'Valencia', countryCode: 'es', countryName: 'Spain' },
  'Seville': { name: 'Seville', countryCode: 'es', countryName: 'Spain' },
  'Zaragoza': { name: 'Zaragoza', countryCode: 'es', countryName: 'Spain' },
  'Málaga': { name: 'Málaga', countryCode: 'es', countryName: 'Spain' },
  'Murcia': { name: 'Murcia', countryCode: 'es', countryName: 'Spain' },
  'Palma': { name: 'Palma', countryCode: 'es', countryName: 'Spain' },
  'Bilbao': { name: 'Bilbao', countryCode: 'es', countryName: 'Spain' },
  'Alicante': { name: 'Alicante', countryCode: 'es', countryName: 'Spain' },
  'Córdoba': { name: 'Córdoba', countryCode: 'es', countryName: 'Spain' },
  'Valladolid': { name: 'Valladolid', countryCode: 'es', countryName: 'Spain' },
  'Vigo': { name: 'Vigo', countryCode: 'es', countryName: 'Spain' },
  'Gijón': { name: 'Gijón', countryCode: 'es', countryName: 'Spain' },
  'Hospitalet de Llobregat': { name: 'Hospitalet de Llobregat', countryCode: 'es', countryName: 'Spain' },
  'La Coruña': { name: 'La Coruña', countryCode: 'es', countryName: 'Spain' },
  'Granada': { name: 'Granada', countryCode: 'es', countryName: 'Spain' },
  'Elche': { name: 'Elche', countryCode: 'es', countryName: 'Spain' },
  'Oviedo': { name: 'Oviedo', countryCode: 'es', countryName: 'Spain' },
  'Santa Cruz de Tenerife': { name: 'Santa Cruz de Tenerife', countryCode: 'es', countryName: 'Spain' },

// Italy
  'Rome': { name: 'Rome', countryCode: 'it', countryName: 'Italy' },
  'Milan': { name: 'Milan', countryCode: 'it', countryName: 'Italy' },
  'Naples': { name: 'Naples', countryCode: 'it', countryName: 'Italy' },
  'Turin': { name: 'Turin', countryCode: 'it', countryName: 'Italy' },
  'Palermo': { name: 'Palermo', countryCode: 'it', countryName: 'Italy' },
  'Genoa': { name: 'Genoa', countryCode: 'it', countryName: 'Italy' },
  'Bologna': { name: 'Bologna', countryCode: 'it', countryName: 'Italy' },
  'Florence': { name: 'Florence', countryCode: 'it', countryName: 'Italy' },
  'Bari': { name: 'Bari', countryCode: 'it', countryName: 'Italy' },
  'Catania': { name: 'Catania', countryCode: 'it', countryName: 'Italy' },
  'Verona': { name: 'Verona', countryCode: 'it', countryName: 'Italy' },
  'Venice': { name: 'Venice', countryCode: 'it', countryName: 'Italy' },
  'Messina': { name: 'Messina', countryCode: 'it', countryName: 'Italy' },
  'Padua': { name: 'Padua', countryCode: 'it', countryName: 'Italy' },
  'Trieste': { name: 'Trieste', countryCode: 'it', countryName: 'Italy' },
  'Brescia': { name: 'Brescia', countryCode: 'it', countryName: 'Italy' },
  'Parma': { name: 'Parma', countryCode: 'it', countryName: 'Italy' },
  'Taranto': { name: 'Taranto', countryCode: 'it', countryName: 'Italy' },
  'Prato': { name: 'Prato', countryCode: 'it', countryName: 'Italy' },
  'Modena': { name: 'Modena', countryCode: 'it', countryName: 'Italy' },

// Russia
  'Moscow': { name: 'Moscow', countryCode: 'ru', countryName: 'Russia' },
  'Saint Petersburg': { name: 'Saint Petersburg', countryCode: 'ru', countryName: 'Russia' },
  'Novosibirsk': { name: 'Novosibirsk', countryCode: 'ru', countryName: 'Russia' },
  'Yekaterinburg': { name: 'Yekaterinburg', countryCode: 'ru', countryName: 'Russia' },
  'Nizhny Novgorod': { name: 'Nizhny Novgorod', countryCode: 'ru', countryName: 'Russia' },
  'Kazan': { name: 'Kazan', countryCode: 'ru', countryName: 'Russia' },
  'Chelyabinsk': { name: 'Chelyabinsk', countryCode: 'ru', countryName: 'Russia' },
  'Samara': { name: 'Samara', countryCode: 'ru', countryName: 'Russia' },
  'Omsk': { name: 'Omsk', countryCode: 'ru', countryName: 'Russia' },
  'Rostov-on-Don': { name: 'Rostov-on-Don', countryCode: 'ru', countryName: 'Russia' },
  'Ufa': { name: 'Ufa', countryCode: 'ru', countryName: 'Russia' },
  'Krasnoyarsk': { name: 'Krasnoyarsk', countryCode: 'ru', countryName: 'Russia' },
  'Perm': { name: 'Perm', countryCode: 'ru', countryName: 'Russia' },
  'Voronezh': { name: 'Voronezh', countryCode: 'ru', countryName: 'Russia' },
  'Volgograd': { name: 'Volgograd', countryCode: 'ru', countryName: 'Russia' },
  'Saratov': { name: 'Saratov', countryCode: 'ru', countryName: 'Russia' },
  'Krasnodar': { name: 'Krasnodar', countryCode: 'ru', countryName: 'Russia' },
  'Tyumen': { name: 'Tyumen', countryCode: 'ru', countryName: 'Russia' },
  'Tolyatti': { name: 'Tolyatti', countryCode: 'ru', countryName: 'Russia' },
  'Izhevsk': { name: 'Izhevsk', countryCode: 'ru', countryName: 'Russia' },

// Turkey
  'Istanbul': { name: 'Istanbul', countryCode: 'tr', countryName: 'Turkey' },
  'Ankara': { name: 'Ankara', countryCode: 'tr', countryName: 'Turkey' },
  'Izmir': { name: 'Izmir', countryCode: 'tr', countryName: 'Turkey' },
  'Bursa': { name: 'Bursa', countryCode: 'tr', countryName: 'Turkey' },
  'Antalya': { name: 'Antalya', countryCode: 'tr', countryName: 'Turkey' },
  'Adana': { name: 'Adana', countryCode: 'tr', countryName: 'Turkey' },
  'Konya': { name: 'Konya', countryCode: 'tr', countryName: 'Turkey' },
  'Gaziantep': { name: 'Gaziantep', countryCode: 'tr', countryName: 'Turkey' },
  'Kayseri': { name: 'Kayseri', countryCode: 'tr', countryName: 'Turkey' },
  'Mersin': { name: 'Mersin', countryCode: 'tr', countryName: 'Turkey' },
  'Eskişehir': { name: 'Eskişehir', countryCode: 'tr', countryName: 'Turkey' },
  'Diyarbakır': { name: 'Diyarbakır', countryCode: 'tr', countryName: 'Turkey' },
  'Samsun': { name: 'Samsun', countryCode: 'tr', countryName: 'Turkey' },
  'Denizli': { name: 'Denizli', countryCode: 'tr', countryName: 'Turkey' },
  'Şanlıurfa': { name: 'Şanlıurfa', countryCode: 'tr', countryName: 'Turkey' },
  'Malatya': { name: 'Malatya', countryCode: 'tr', countryName: 'Turkey' },
  'Erzurum': { name: 'Erzurum', countryCode: 'tr', countryName: 'Turkey' },
  'Sakarya': { name: 'Sakarya', countryCode: 'tr', countryName: 'Turkey' },
  'Trabzon': { name: 'Trabzon', countryCode: 'tr', countryName: 'Turkey' },
  'Manisa': { name: 'Manisa', countryCode: 'tr', countryName: 'Turkey' },

// Iran
  'Tehran': { name: 'Tehran', countryCode: 'ir', countryName: 'Iran' },
  'Mashhad': { name: 'Mashhad', countryCode: 'ir', countryName: 'Iran' },
  'Isfahan': { name: 'Isfahan', countryCode: 'ir', countryName: 'Iran' },
  'Karaj': { name: 'Karaj', countryCode: 'ir', countryName: 'Iran' },
  'Tabriz': { name: 'Tabriz', countryCode: 'ir', countryName: 'Iran' },
  'Shiraz': { name: 'Shiraz', countryCode: 'ir', countryName: 'Iran' },
  'Qom': { name: 'Qom', countryCode: 'ir', countryName: 'Iran' },
  'Ahvaz': { name: 'Ahvaz', countryCode: 'ir', countryName: 'Iran' },
  'Kermanshah': { name: 'Kermanshah', countryCode: 'ir', countryName: 'Iran' },
  'Urmia': { name: 'Urmia', countryCode: 'ir', countryName: 'Iran' },
  'Rasht': { name: 'Rasht', countryCode: 'ir', countryName: 'Iran' },
  'Kerman': { name: 'Kerman', countryCode: 'ir', countryName: 'Iran' },
  'Hamadan': { name: 'Hamadan', countryCode: 'ir', countryName: 'Iran' },
  'Yazd': { name: 'Yazd', countryCode: 'ir', countryName: 'Iran' },
  'Arak': { name: 'Arak', countryCode: 'ir', countryName: 'Iran' },
  'Bandar Abbas': { name: 'Bandar Abbas', countryCode: 'ir', countryName: 'Iran' },
  'Zanjan': { name: 'Zanjan', countryCode: 'ir', countryName: 'Iran' },
  'Sanandaj': { name: 'Sanandaj', countryCode: 'ir', countryName: 'Iran' },
  'Khorramabad': { name: 'Khorramabad', countryCode: 'ir', countryName: 'Iran' },
  'Gorgan': { name: 'Gorgan', countryCode: 'ir', countryName: 'Iran' },

// India
  'Mumbai': { name: 'Mumbai', countryCode: 'in', countryName: 'India' },
  'Delhi': { name: 'Delhi', countryCode: 'in', countryName: 'India' },
  'Bangalore': { name: 'Bangalore', countryCode: 'in', countryName: 'India' },
  'Hyderabad': { name: 'Hyderabad', countryCode: 'in', countryName: 'India' },
  'Ahmedabad': { name: 'Ahmedabad', countryCode: 'in', countryName: 'India' },
  'Chennai': { name: 'Chennai', countryCode: 'in', countryName: 'India' },
  'Kolkata': { name: 'Kolkata', countryCode: 'in', countryName: 'India' },
  'Surat': { name: 'Surat', countryCode: 'in', countryName: 'India' },
  'Pune': { name: 'Pune', countryCode: 'in', countryName: 'India' },
  'Jaipur': { name: 'Jaipur', countryCode: 'in', countryName: 'India' },
  'Lucknow': { name: 'Lucknow', countryCode: 'in', countryName: 'India' },
  'Kanpur': { name: 'Kanpur', countryCode: 'in', countryName: 'India' },
  'Nagpur': { name: 'Nagpur', countryCode: 'in', countryName: 'India' },
  'Indore': { name: 'Indore', countryCode: 'in', countryName: 'India' },
  'Thane': { name: 'Thane', countryCode: 'in', countryName: 'India' },
  'Bhopal': { name: 'Bhopal', countryCode: 'in', countryName: 'India' },
  'Visakhapatnam': { name: 'Visakhapatnam', countryCode: 'in', countryName: 'India' },
  'Patna': { name: 'Patna', countryCode: 'in', countryName: 'India' },
  'Vadodara': { name: 'Vadodara', countryCode: 'in', countryName: 'India' },
  'Ludhiana': { name: 'Ludhiana', countryCode: 'in', countryName: 'India' },

};

/**
 * Get country code by city name
 */
export function getCountryCode(cityName: string): string {
  return cityMapping[cityName]?.countryCode || 'gb';
}

/**
 * Get country name by city name
 */
export function getCountryName(cityName: string): string {
  return cityMapping[cityName]?.countryName || 'United Kingdom';
}