/**
 * financeService.ts
 *
 * High-level finance client wrapper.
 *
 * Responsibilities:
 * - Provide a single helper to call the server finance RPC with an autogenerated
 *   idempotency key and authenticated request header (Authorization: Bearer ...).
 * - Normalize results to a predictable shape for UI code.
 * - Expose a tiny dev helper on window for manual verification in the browser devtools.
 *
 * Notes:
 * - This file wraps the existing financeApply helper (which calls /.netlify/functions/finance-apply).
 * - Idempotency keys are UUIDv4 (best-effort without external libs).
 * - Token retrieval uses the app's getUserAccessToken helper when available.
 */

/**
 * Module-level comments and imports
 */
import { financeApply, FinanceApplyParams, FinanceApplyResult } from './financeClient';
import getUserAccessToken from './getUserAccessToken';

/**
 * ApplyResult
 * @description Normalized wrapper around RPC call result returned to callers.
 */
export interface ApplyResult {
  success: boolean;
  idempotencyKey: string;
  transaction?: any | null;
  newBalanceCents?: number | null;
  error?: string | null;
}

/**
 * generateIdempotencyKey
 * @description Create a RFC-4122 style UUID v4 string using browser crypto when available.
 *              This is used as the idempotency key for finance RPC calls to avoid duplicates.
 */
export function generateIdempotencyKey(): string {
  // Use crypto API if present (recommended)
  if (typeof crypto !== 'undefined' && typeof crypto.getRandomValues === 'function') {
    const bytes = new Uint8Array(16);
    crypto.getRandomValues(bytes);
    // Per RFC-4122 v4: set version and variant bits
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    const hex = Array.from(bytes).map((b) => b.toString(16).padStart(2, '0')).join('');
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
  }

  // Fallback: Math.random based UUID (not cryptographically secure but fine for idempotency keys)
  const randHex = () => Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  return `${randHex()}${randHex()}-${randHex()}-${randHex()}-${randHex()}-${randHex()}${randHex()}${randHex()}`;
}

/**
 * applyFinance
 * @description High-level wrapper to apply a finance delta on the server.
 *
 * @param params Partial<FinanceApplyParams> where:
 *  - companyId: string (required)
 *  - deltaCents: number (required) - cents (integer)
 *  - type: string (required) - one of your allowed types (income/expense/loan/repayment/...)
 *  - description?: string
 *  - meta?: any (optional object)
 *  - idempotencyKey?: string (optional) - if omitted one will be generated
 *
 * @returns Promise<ApplyResult>
 */
export async function applyFinance(params: Partial<FinanceApplyParams>): Promise<ApplyResult> {
  // Basic validation
  if (!params || typeof params.companyId !== 'string' || (!Number.isFinite(params.deltaCents) && typeof params.deltaCents !== 'number')) {
    return { success: false, idempotencyKey: '', error: 'Invalid parameters (companyId and deltaCents are required)' };
  }

  const idempotencyKey = (params as any).idempotencyKey || generateIdempotencyKey();

  // Attempt to obtain user token for Authorization header
  let token: string | null = null;
  try {
    token = getUserAccessToken ? getUserAccessToken() : null;
  } catch {
    token = null;
  }

  const rpcParams: FinanceApplyParams = {
    companyId: params.companyId!,
    deltaCents: Math.round(Number(params.deltaCents)),
    type: (params.type as string) || 'adjustment',
    description: params.description ?? null,
    idempotencyKey,
    meta: (params as any)?.meta ?? undefined,
    token: token ?? undefined
  };

  try {
    const res: FinanceApplyResult = await financeApply(rpcParams);
    if (!res || !res.success) {
      return {
        success: false,
        idempotencyKey,
        transaction: res?.transaction ?? null,
        newBalanceCents: res?.newBalanceCents ?? null,
        error: res?.error ? String(res.error) : 'Unknown server error'
      };
    }

    return {
      success: true,
      idempotencyKey,
      transaction: res.transaction ?? null,
      newBalanceCents: typeof res.newBalanceCents === 'number' ? Math.round(res.newBalanceCents) : null,
      error: null
    };
  } catch (err: any) {
    return {
      success: false,
      idempotencyKey,
      transaction: null,
      newBalanceCents: null,
      error: err?.message ? String(err.message) : String(err)
    };
  }
}

/**
 * devExposeTestHelper
 * @description Expose a tiny test helper on window.__applyFinanceTest for manual dev testing.
 *              This is only created when running in a browser environment.
 *
 * Usage (from browser console):
 *   window.__applyFinanceTest({ companyId: '...', deltaCents: -100000, type: 'expense', description: 'Test purchase' })
 *
 * The helper returns a Promise that resolves to the ApplyResult object.
 */
function devExposeTestHelper() {
  if (typeof window === 'undefined') return;
  // @ts-ignore - attach to window for manual testing in dev
  if (!window.__applyFinanceTest) {
    // @ts-ignore
    window.__applyFinanceTest = applyFinance;
  }
}

// Expose test helper automatically (safe noop server-side)
devExposeTestHelper();

/**
 * Export default for convenience
 */
export default {
  applyFinance,
  generateIdempotencyKey
};